// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package verse

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/Khan/genqlient/graphql"
)

type ActivityEntryType string

const (
	ActivityEntryTypePmSale            ActivityEntryType = "PM_SALE"
	ActivityEntryTypeSmListed          ActivityEntryType = "SM_LISTED"
	ActivityEntryTypeSmDelisted        ActivityEntryType = "SM_DELISTED"
	ActivityEntryTypeSmSale            ActivityEntryType = "SM_SALE"
	ActivityEntryTypeSmOffer           ActivityEntryType = "SM_OFFER"
	ActivityEntryTypeSmGlobalOffer     ActivityEntryType = "SM_GLOBAL_OFFER"
	ActivityEntryTypeOsSale            ActivityEntryType = "OS_SALE"
	ActivityEntryTypeOsOffer           ActivityEntryType = "OS_OFFER"
	ActivityEntryTypeOsCollectionOffer ActivityEntryType = "OS_COLLECTION_OFFER"
	ActivityEntryTypeOsListed          ActivityEntryType = "OS_LISTED"
)

// ActivityPageActivityPageActivityEntryConnection includes the requested fields of the GraphQL type ActivityEntryConnection.
type ActivityPageActivityPageActivityEntryConnection struct {
	Nodes    []ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry `json:"nodes"`
	PageInfo ActivityPageActivityPageActivityEntryConnectionPageInfo             `json:"pageInfo"`
}

// GetNodes returns ActivityPageActivityPageActivityEntryConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnection) GetNodes() []ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry {
	return v.Nodes
}

// GetPageInfo returns ActivityPageActivityPageActivityEntryConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnection) GetPageInfo() ActivityPageActivityPageActivityEntryConnectionPageInfo {
	return v.PageInfo
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry includes the requested fields of the GraphQL type ActivityEntry.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry struct {
	Id                    string                                                                                 `json:"id"`
	Amount                string                                                                                 `json:"amount"`
	TransactionHash       *string                                                                                `json:"transactionHash"`
	ToUserId              *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToUserIdUserPublic   `json:"toUserId"`
	FromUserId            *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromUserIdUserPublic `json:"fromUserId"`
	FromEthereumAddress   *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromEthereumAddress  `json:"fromEthereumAddress"`
	ToEthereumAddress     *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToEthereumAddress    `json:"toEthereumAddress"`
	FromBlockchainAddress *string                                                                                `json:"fromBlockchainAddress"`
	EntryType             ActivityEntryType                                                                      `json:"entryType"`
	Timestamp             time.Time                                                                              `json:"timestamp"`
	ToBlockchainAddress   *string                                                                                `json:"toBlockchainAddress"`
	Artwork               ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtwork               `json:"artwork"`
	Asset                 *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset                `json:"asset"`
}

// GetId returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry.Id, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry) GetId() string {
	return v.Id
}

// GetAmount returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry.Amount, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry) GetAmount() string {
	return v.Amount
}

// GetTransactionHash returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry.TransactionHash, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry) GetTransactionHash() *string {
	return v.TransactionHash
}

// GetToUserId returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry.ToUserId, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry) GetToUserId() *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToUserIdUserPublic {
	return v.ToUserId
}

// GetFromUserId returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry.FromUserId, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry) GetFromUserId() *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromUserIdUserPublic {
	return v.FromUserId
}

// GetFromEthereumAddress returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry.FromEthereumAddress, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry) GetFromEthereumAddress() *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromEthereumAddress {
	return v.FromEthereumAddress
}

// GetToEthereumAddress returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry.ToEthereumAddress, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry) GetToEthereumAddress() *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToEthereumAddress {
	return v.ToEthereumAddress
}

// GetFromBlockchainAddress returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry.FromBlockchainAddress, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry) GetFromBlockchainAddress() *string {
	return v.FromBlockchainAddress
}

// GetEntryType returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry.EntryType, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry) GetEntryType() ActivityEntryType {
	return v.EntryType
}

// GetTimestamp returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry.Timestamp, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry) GetTimestamp() time.Time {
	return v.Timestamp
}

// GetToBlockchainAddress returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry.ToBlockchainAddress, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry) GetToBlockchainAddress() *string {
	return v.ToBlockchainAddress
}

// GetArtwork returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry.Artwork, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry) GetArtwork() ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtwork {
	return v.Artwork
}

// GetAsset returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry.Asset, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntry) GetAsset() *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset {
	return v.Asset
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtwork includes the requested fields of the GraphQL type Artwork.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtwork struct {
	Id     string                                                                                `json:"id"`
	Title  *string                                                                               `json:"title"`
	Artist *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtworkArtistPerson `json:"artist"`
}

// GetId returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtwork.Id, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtwork) GetId() string {
	return v.Id
}

// GetTitle returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtwork.Title, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtwork) GetTitle() *string {
	return v.Title
}

// GetArtist returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtwork.Artist, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtwork) GetArtist() *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtworkArtistPerson {
	return v.Artist
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtworkArtistPerson includes the requested fields of the GraphQL type Person.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtworkArtistPerson struct {
	Slug string `json:"slug"`
}

// GetSlug returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtworkArtistPerson.Slug, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryArtworkArtistPerson) GetSlug() string {
	return v.Slug
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset includes the requested fields of the GraphQL type Asset.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset struct {
	Id        string                                                                                    `json:"id"`
	AssetType AssetType                                                                                 `json:"assetType"`
	Asset     ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive `json:"-"`
}

// GetId returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset.Id, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset) GetId() string {
	return v.Id
}

// GetAssetType returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset.AssetType, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset) GetAssetType() AssetType {
	return v.AssetType
}

// GetAsset returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset.Asset, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset) GetAsset() ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive {
	return v.Asset
}

func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset
		Asset json.RawMessage `json:"asset"`
		graphql.NoUnmarshalJSON
	}
	firstPass.ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Asset
		src := firstPass.Asset
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset.Asset: %w", err)
			}
		}
	}
	return nil
}

type __premarshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset struct {
	Id string `json:"id"`

	AssetType AssetType `json:"assetType"`

	Asset json.RawMessage `json:"asset"`
}

func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset) __premarshalJSON() (*__premarshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset, error) {
	var retval __premarshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset

	retval.Id = v.Id
	retval.AssetType = v.AssetType
	{

		dst := &retval.Asset
		src := v.Asset
		var err error
		*dst, err = __marshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAsset.Asset: %w", err)
		}
	}
	return &retval, nil
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive includes the requested fields of the GraphQL interface AssetPrimitive.
//
// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive is implemented by the following types:
// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetBookmark
// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive interface {
	implementsGraphQLInterfaceActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() *string
}

func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetBookmark) implementsGraphQLInterfaceActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive() {
}
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition) implementsGraphQLInterfaceActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive() {
}

func __unmarshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive(b []byte, v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Bookmark":
		*v = new(ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetBookmark)
		return json.Unmarshal(b, *v)
	case "Edition":
		*v = new(ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing AssetPrimitive.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive: "%v"`, tn.TypeName)
	}
}

func __marshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive(v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetBookmark:
		typename = "Bookmark"

		result := struct {
			TypeName string `json:"__typename"`
			*ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetBookmark
		}{typename, v}
		return json.Marshal(result)
	case *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition:
		typename = "Edition"

		premarshaled, err := v.__premarshalJSON()
		if err != nil {
			return nil, err
		}
		result := struct {
			TypeName string `json:"__typename"`
			*__premarshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition
		}{typename, premarshaled}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetAssetPrimitive: "%T"`, v)
	}
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetBookmark includes the requested fields of the GraphQL type Bookmark.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetBookmark struct {
	Typename *string `json:"__typename"`
	Hash     string  `json:"hash"`
}

// GetTypename returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetBookmark.Typename, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetBookmark) GetTypename() *string {
	return v.Typename
}

// GetHash returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetBookmark.Hash, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetBookmark) GetHash() string {
	return v.Hash
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition includes the requested fields of the GraphQL type Edition.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition struct {
	Typename *string `json:"__typename"`
	// ID of Edition on the blockchain. Assets service generate this field on its own
	TokenId *string `json:"tokenId"`
	// № of Edition. To show a person something like "you own Edition #4 of 20"
	// Assets service deduct edition number on its own, based on how many editions there are for primaryMarketListingId
	EditionNumber int                                                                                            `json:"editionNumber"`
	Title         *string                                                                                        `json:"title"`
	StaticAsset   *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset `json:"-"`
	Artwork       ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtwork      `json:"artwork"`
}

// GetTypename returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition.Typename, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition) GetTypename() *string {
	return v.Typename
}

// GetTokenId returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition.TokenId, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition) GetTokenId() *string {
	return v.TokenId
}

// GetEditionNumber returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition.EditionNumber, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition) GetEditionNumber() int {
	return v.EditionNumber
}

// GetTitle returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition.Title, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition) GetTitle() *string {
	return v.Title
}

// GetStaticAsset returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition.StaticAsset, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition) GetStaticAsset() *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset {
	return v.StaticAsset
}

// GetArtwork returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition.Artwork, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition) GetArtwork() ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtwork {
	return v.Artwork
}

func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition
		StaticAsset json.RawMessage `json:"staticAsset"`
		graphql.NoUnmarshalJSON
	}
	firstPass.ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.StaticAsset
		src := firstPass.StaticAsset
		if len(src) != 0 && string(src) != "null" {
			*dst = new(ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset)
			err = __unmarshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset(
				src, *dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition.StaticAsset: %w", err)
			}
		}
	}
	return nil
}

type __premarshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition struct {
	Typename *string `json:"__typename"`

	TokenId *string `json:"tokenId"`

	EditionNumber int `json:"editionNumber"`

	Title *string `json:"title"`

	StaticAsset json.RawMessage `json:"staticAsset"`

	Artwork ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtwork `json:"artwork"`
}

func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition) __premarshalJSON() (*__premarshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition, error) {
	var retval __premarshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition

	retval.Typename = v.Typename
	retval.TokenId = v.TokenId
	retval.EditionNumber = v.EditionNumber
	retval.Title = v.Title
	{

		dst := &retval.StaticAsset
		src := v.StaticAsset
		if src != nil {
			var err error
			*dst, err = __marshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset(
				src)
			if err != nil {
				return nil, fmt.Errorf(
					"unable to marshal ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEdition.StaticAsset: %w", err)
			}
		}
	}
	retval.Artwork = v.Artwork
	return &retval, nil
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtwork includes the requested fields of the GraphQL type Artwork.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtwork struct {
	Collection *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollection   `json:"collection"`
	Artist     *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkArtistPerson `json:"artist"`
}

// GetCollection returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtwork.Collection, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtwork) GetCollection() *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollection {
	return v.Collection
}

// GetArtist returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtwork.Artist, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtwork) GetArtist() *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkArtistPerson {
	return v.Artist
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkArtistPerson includes the requested fields of the GraphQL type Person.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkArtistPerson struct {
	Name *string `json:"name"`
	Slug string  `json:"slug"`
}

// GetName returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkArtistPerson.Name, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkArtistPerson) GetName() *string {
	return v.Name
}

// GetSlug returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkArtistPerson.Slug, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkArtistPerson) GetSlug() string {
	return v.Slug
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollection includes the requested fields of the GraphQL type Collection.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollection struct {
	Name    *string                                                                                                            `json:"name"`
	Slug    string                                                                                                             `json:"slug"`
	Persons []ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollectionPersonsPerson `json:"persons"`
}

// GetName returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollection.Name, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollection) GetName() *string {
	return v.Name
}

// GetSlug returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollection.Slug, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollection) GetSlug() string {
	return v.Slug
}

// GetPersons returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollection.Persons, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollection) GetPersons() []ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollectionPersonsPerson {
	return v.Persons
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollectionPersonsPerson includes the requested fields of the GraphQL type Person.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollectionPersonsPerson struct {
	Slug string `json:"slug"`
}

// GetSlug returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollectionPersonsPerson.Slug, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionArtworkCollectionPersonsPerson) GetSlug() string {
	return v.Slug
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset includes the requested fields of the GraphQL interface StaticAsset.
//
// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset is implemented by the following types:
// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset
// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset
// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset
// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset
// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset interface {
	implementsGraphQLInterfaceActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() *string
}

func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset) implementsGraphQLInterfaceActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset() {
}
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset) implementsGraphQLInterfaceActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset() {
}
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) implementsGraphQLInterfaceActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset() {
}
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset) implementsGraphQLInterfaceActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset() {
}
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) implementsGraphQLInterfaceActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset() {
}

func __unmarshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset(b []byte, v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "AudioAsset":
		*v = new(ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset)
		return json.Unmarshal(b, *v)
	case "IFrameAsset":
		*v = new(ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset)
		return json.Unmarshal(b, *v)
	case "ImageAsset":
		*v = new(ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset)
		return json.Unmarshal(b, *v)
	case "SVGAsset":
		*v = new(ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset)
		return json.Unmarshal(b, *v)
	case "VideoAsset":
		*v = new(ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing StaticAsset.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset: "%v"`, tn.TypeName)
	}
}

func __marshalActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset(v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset:
		typename = "AudioAsset"

		result := struct {
			TypeName string `json:"__typename"`
			*ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset
		}{typename, v}
		return json.Marshal(result)
	case *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset:
		typename = "IFrameAsset"

		result := struct {
			TypeName string `json:"__typename"`
			*ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset
		}{typename, v}
		return json.Marshal(result)
	case *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset:
		typename = "ImageAsset"

		result := struct {
			TypeName string `json:"__typename"`
			*ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset
		}{typename, v}
		return json.Marshal(result)
	case *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset:
		typename = "SVGAsset"

		result := struct {
			TypeName string `json:"__typename"`
			*ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset
		}{typename, v}
		return json.Marshal(result)
	case *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset:
		typename = "VideoAsset"

		result := struct {
			TypeName string `json:"__typename"`
			*ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAsset: "%T"`, v)
	}
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset includes the requested fields of the GraphQL type AudioAsset.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset struct {
	Typename      *string  `json:"__typename"`
	Id            string   `json:"id"`
	BaseUrl       string   `json:"baseUrl"`
	Duration      *float64 `json:"duration"`
	MimeType      *string  `json:"mimeType"`
	FileSize      *int     `json:"fileSize"`
	InternalTitle *string  `json:"internalTitle"`
}

// GetTypename returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset.Typename, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset) GetTypename() *string {
	return v.Typename
}

// GetId returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset.Id, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset) GetId() string {
	return v.Id
}

// GetBaseUrl returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset.BaseUrl, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset) GetBaseUrl() string {
	return v.BaseUrl
}

// GetDuration returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset.Duration, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset) GetDuration() *float64 {
	return v.Duration
}

// GetMimeType returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset.MimeType, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset) GetMimeType() *string {
	return v.MimeType
}

// GetFileSize returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset.FileSize, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset) GetFileSize() *int {
	return v.FileSize
}

// GetInternalTitle returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset.InternalTitle, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetAudioAsset) GetInternalTitle() *string {
	return v.InternalTitle
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset includes the requested fields of the GraphQL type IFrameAsset.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset struct {
	Typename        *string  `json:"__typename"`
	Id              string   `json:"id"`
	IframeUrl       string   `json:"iframeUrl"`
	BaseUrl         string   `json:"baseUrl"`
	PreviewS3Key    string   `json:"previewS3Key"`
	PreviewImageUrl string   `json:"previewImageUrl"`
	AspectRatio     *float64 `json:"aspectRatio"`
	Caption         *string  `json:"caption"`
	InternalTitle   *string  `json:"internalTitle"`
}

// GetTypename returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset.Typename, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset) GetTypename() *string {
	return v.Typename
}

// GetId returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset.Id, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset) GetId() string {
	return v.Id
}

// GetIframeUrl returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset.IframeUrl, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset) GetIframeUrl() string {
	return v.IframeUrl
}

// GetBaseUrl returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset.BaseUrl, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset) GetBaseUrl() string {
	return v.BaseUrl
}

// GetPreviewS3Key returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset.PreviewS3Key, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset) GetPreviewS3Key() string {
	return v.PreviewS3Key
}

// GetPreviewImageUrl returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset.PreviewImageUrl, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset) GetPreviewImageUrl() string {
	return v.PreviewImageUrl
}

// GetAspectRatio returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset.AspectRatio, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset) GetAspectRatio() *float64 {
	return v.AspectRatio
}

// GetCaption returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset.Caption, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset) GetCaption() *string {
	return v.Caption
}

// GetInternalTitle returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset.InternalTitle, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetIFrameAsset) GetInternalTitle() *string {
	return v.InternalTitle
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset includes the requested fields of the GraphQL type ImageAsset.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset struct {
	Typename      *string  `json:"__typename"`
	Id            string   `json:"id"`
	BaseUrl       string   `json:"baseUrl"`
	S3Key         *string  `json:"s3Key"`
	Author        *string  `json:"author"`
	Caption       *string  `json:"caption"`
	AspectRatio   *float64 `json:"aspectRatio"`
	Width         *int     `json:"width"`
	Height        *int     `json:"height"`
	MimeType      *string  `json:"mimeType"`
	FileSize      *int     `json:"fileSize"`
	InternalTitle *string  `json:"internalTitle"`
	IsGif         bool     `json:"isGif"`
}

// GetTypename returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset.Typename, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) GetTypename() *string {
	return v.Typename
}

// GetId returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset.Id, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) GetId() string {
	return v.Id
}

// GetBaseUrl returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset.BaseUrl, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) GetBaseUrl() string {
	return v.BaseUrl
}

// GetS3Key returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset.S3Key, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) GetS3Key() *string {
	return v.S3Key
}

// GetAuthor returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset.Author, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) GetAuthor() *string {
	return v.Author
}

// GetCaption returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset.Caption, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) GetCaption() *string {
	return v.Caption
}

// GetAspectRatio returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset.AspectRatio, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) GetAspectRatio() *float64 {
	return v.AspectRatio
}

// GetWidth returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset.Width, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) GetWidth() *int {
	return v.Width
}

// GetHeight returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset.Height, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) GetHeight() *int {
	return v.Height
}

// GetMimeType returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset.MimeType, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) GetMimeType() *string {
	return v.MimeType
}

// GetFileSize returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset.FileSize, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) GetFileSize() *int {
	return v.FileSize
}

// GetInternalTitle returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset.InternalTitle, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) GetInternalTitle() *string {
	return v.InternalTitle
}

// GetIsGif returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset.IsGif, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetImageAsset) GetIsGif() bool {
	return v.IsGif
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset includes the requested fields of the GraphQL type SVGAsset.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset struct {
	Typename           *string  `json:"__typename"`
	Id                 string   `json:"id"`
	BaseUrl            string   `json:"baseUrl"`
	S3Key              *string  `json:"s3Key"`
	PreviewS3Key       string   `json:"previewS3Key"`
	PreviewImageUrl    string   `json:"previewImageUrl"`
	Author             *string  `json:"author"`
	Caption            *string  `json:"caption"`
	PreviewAspectRatio *float64 `json:"previewAspectRatio"`
	MimeType           *string  `json:"mimeType"`
	FileSize           *int     `json:"fileSize"`
	InternalTitle      *string  `json:"internalTitle"`
}

// GetTypename returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset.Typename, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset) GetTypename() *string {
	return v.Typename
}

// GetId returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset.Id, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset) GetId() string {
	return v.Id
}

// GetBaseUrl returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset.BaseUrl, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset) GetBaseUrl() string {
	return v.BaseUrl
}

// GetS3Key returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset.S3Key, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset) GetS3Key() *string {
	return v.S3Key
}

// GetPreviewS3Key returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset.PreviewS3Key, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset) GetPreviewS3Key() string {
	return v.PreviewS3Key
}

// GetPreviewImageUrl returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset.PreviewImageUrl, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset) GetPreviewImageUrl() string {
	return v.PreviewImageUrl
}

// GetAuthor returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset.Author, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset) GetAuthor() *string {
	return v.Author
}

// GetCaption returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset.Caption, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset) GetCaption() *string {
	return v.Caption
}

// GetPreviewAspectRatio returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset.PreviewAspectRatio, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset) GetPreviewAspectRatio() *float64 {
	return v.PreviewAspectRatio
}

// GetMimeType returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset.MimeType, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset) GetMimeType() *string {
	return v.MimeType
}

// GetFileSize returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset.FileSize, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset) GetFileSize() *int {
	return v.FileSize
}

// GetInternalTitle returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset.InternalTitle, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetSVGAsset) GetInternalTitle() *string {
	return v.InternalTitle
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset includes the requested fields of the GraphQL type VideoAsset.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset struct {
	Typename           *string  `json:"__typename"`
	Id                 string   `json:"id"`
	BaseUrl            string   `json:"baseUrl"`
	S3Key              *string  `json:"s3Key"`
	PreviewS3Key       string   `json:"previewS3Key"`
	PreviewImageUrl    string   `json:"previewImageUrl"`
	Author             *string  `json:"author"`
	Caption            *string  `json:"caption"`
	PreviewAspectRatio *float64 `json:"previewAspectRatio"`
	Width              *int     `json:"width"`
	Height             *int     `json:"height"`
	MimeType           *string  `json:"mimeType"`
	FileSize           *int     `json:"fileSize"`
	InternalTitle      *string  `json:"internalTitle"`
}

// GetTypename returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.Typename, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetTypename() *string {
	return v.Typename
}

// GetId returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.Id, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetId() string {
	return v.Id
}

// GetBaseUrl returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.BaseUrl, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetBaseUrl() string {
	return v.BaseUrl
}

// GetS3Key returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.S3Key, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetS3Key() *string {
	return v.S3Key
}

// GetPreviewS3Key returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.PreviewS3Key, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetPreviewS3Key() string {
	return v.PreviewS3Key
}

// GetPreviewImageUrl returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.PreviewImageUrl, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetPreviewImageUrl() string {
	return v.PreviewImageUrl
}

// GetAuthor returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.Author, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetAuthor() *string {
	return v.Author
}

// GetCaption returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.Caption, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetCaption() *string {
	return v.Caption
}

// GetPreviewAspectRatio returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.PreviewAspectRatio, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetPreviewAspectRatio() *float64 {
	return v.PreviewAspectRatio
}

// GetWidth returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.Width, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetWidth() *int {
	return v.Width
}

// GetHeight returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.Height, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetHeight() *int {
	return v.Height
}

// GetMimeType returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.MimeType, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetMimeType() *string {
	return v.MimeType
}

// GetFileSize returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.FileSize, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetFileSize() *int {
	return v.FileSize
}

// GetInternalTitle returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset.InternalTitle, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryAssetAssetEditionStaticAssetVideoAsset) GetInternalTitle() *string {
	return v.InternalTitle
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromEthereumAddress includes the requested fields of the GraphQL type EthereumAddress.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromEthereumAddress struct {
	Address string  `json:"address"`
	EnsName *string `json:"ensName"`
}

// GetAddress returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromEthereumAddress.Address, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromEthereumAddress) GetAddress() string {
	return v.Address
}

// GetEnsName returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromEthereumAddress.EnsName, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromEthereumAddress) GetEnsName() *string {
	return v.EnsName
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromUserIdUserPublic includes the requested fields of the GraphQL type UserPublic.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromUserIdUserPublic struct {
	Username *string `json:"username"`
}

// GetUsername returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromUserIdUserPublic.Username, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryFromUserIdUserPublic) GetUsername() *string {
	return v.Username
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToEthereumAddress includes the requested fields of the GraphQL type EthereumAddress.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToEthereumAddress struct {
	Address string  `json:"address"`
	EnsName *string `json:"ensName"`
}

// GetAddress returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToEthereumAddress.Address, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToEthereumAddress) GetAddress() string {
	return v.Address
}

// GetEnsName returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToEthereumAddress.EnsName, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToEthereumAddress) GetEnsName() *string {
	return v.EnsName
}

// ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToUserIdUserPublic includes the requested fields of the GraphQL type UserPublic.
type ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToUserIdUserPublic struct {
	Username *string `json:"username"`
}

// GetUsername returns ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToUserIdUserPublic.Username, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionNodesActivityEntryToUserIdUserPublic) GetUsername() *string {
	return v.Username
}

// ActivityPageActivityPageActivityEntryConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type ActivityPageActivityPageActivityEntryConnectionPageInfo struct {
	EndCursor   *string `json:"endCursor"`
	HasNextPage bool    `json:"hasNextPage"`
}

// GetEndCursor returns ActivityPageActivityPageActivityEntryConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionPageInfo) GetEndCursor() *string {
	return v.EndCursor
}

// GetHasNextPage returns ActivityPageActivityPageActivityEntryConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *ActivityPageActivityPageActivityEntryConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

type ActivityPageFilter struct {
	ActivityType []ActivityEntryType `json:"activityType"`
	AssetType    *AssetType          `json:"assetType"`
}

// GetActivityType returns ActivityPageFilter.ActivityType, and is useful for accessing the field via an interface.
func (v *ActivityPageFilter) GetActivityType() []ActivityEntryType { return v.ActivityType }

// GetAssetType returns ActivityPageFilter.AssetType, and is useful for accessing the field via an interface.
func (v *ActivityPageFilter) GetAssetType() *AssetType { return v.AssetType }

// ActivityPageResponse is returned by ActivityPage on success.
type ActivityPageResponse struct {
	ActivityPage ActivityPageActivityPageActivityEntryConnection `json:"activityPage"`
}

// GetActivityPage returns ActivityPageResponse.ActivityPage, and is useful for accessing the field via an interface.
func (v *ActivityPageResponse) GetActivityPage() ActivityPageActivityPageActivityEntryConnection {
	return v.ActivityPage
}

type AssetType string

const (
	AssetTypeEdition  AssetType = "EDITION"
	AssetTypeBookmark AssetType = "BOOKMARK"
)

// __ActivityPageInput is used internally by genqlient
type __ActivityPageInput struct {
	After  *string             `json:"after"`
	Filter *ActivityPageFilter `json:"filter"`
}

// GetAfter returns __ActivityPageInput.After, and is useful for accessing the field via an interface.
func (v *__ActivityPageInput) GetAfter() *string { return v.After }

// GetFilter returns __ActivityPageInput.Filter, and is useful for accessing the field via an interface.
func (v *__ActivityPageInput) GetFilter() *ActivityPageFilter { return v.Filter }

// The query or mutation executed by ActivityPage.
const ActivityPage_Operation = `
query ActivityPage ($after: Cursor, $filter: ActivityPageFilter) {
	activityPage(first: 50, after: $after, filter: $filter) {
		nodes {
			id
			amount
			transactionHash
			toUserId {
				username
			}
			fromUserId {
				username
			}
			fromEthereumAddress {
				address
				ensName
			}
			toEthereumAddress {
				address
				ensName
			}
			fromBlockchainAddress
			entryType
			timestamp
			toBlockchainAddress
			artwork {
				id
				title
				artist {
					slug
				}
			}
			asset {
				id
				assetType
				asset {
					__typename
					... on Bookmark {
						hash
					}
					... on Edition {
						tokenId
						editionNumber
						title
						staticAsset {
							__typename
							... on VideoAsset {
								id
								baseUrl
								s3Key
								previewS3Key
								previewImageUrl
								author
								caption
								previewAspectRatio
								width
								height
								mimeType
								fileSize
								internalTitle
							}
							... on ImageAsset {
								id
								baseUrl
								s3Key
								author
								caption
								aspectRatio
								width
								height
								mimeType
								fileSize
								internalTitle
								isGif
							}
							... on SVGAsset {
								id
								baseUrl
								s3Key
								previewS3Key
								previewImageUrl
								author
								caption
								previewAspectRatio
								mimeType
								fileSize
								internalTitle
							}
							... on AudioAsset {
								id
								baseUrl
								duration
								mimeType
								fileSize
								internalTitle
							}
							... on IFrameAsset {
								id
								iframeUrl
								baseUrl
								previewS3Key
								previewImageUrl
								aspectRatio
								caption
								internalTitle
							}
						}
						artwork {
							collection {
								name
								slug
								persons {
									slug
								}
							}
							artist {
								name
								slug
							}
						}
					}
				}
			}
		}
		pageInfo {
			endCursor
			hasNextPage
		}
	}
}
`

func ActivityPage(
	ctx_ context.Context,
	client_ graphql.Client,
	after *string,
	filter *ActivityPageFilter,
) (*ActivityPageResponse, error) {
	req_ := &graphql.Request{
		OpName: "ActivityPage",
		Query:  ActivityPage_Operation,
		Variables: &__ActivityPageInput{
			After:  after,
			Filter: filter,
		},
	}
	var err_ error

	var data_ ActivityPageResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
